name: Terraform Deployment

on:
  workflow_dispatch  # Manual trigger via GitHub UI

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
      TF_VAR_ami_id: ${{ secrets.AMI_ID }}
      TF_VAR_instance_type: ${{ secrets.INSTANCE_TYPE }}
      TF_VAR_key_name: ${{ secrets.KEY_NAME }}
      TF_VAR_security_group_id: ${{ secrets.SECURITY_GROUP_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Export AWS Credentials
        run: |
         echo "AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY_ID }}" >> $GITHUB_ENV
         echo "AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
         echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV

      - name: Print AWS envs (for debugging)
        run: env | grep AWS


      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6  # or your desired version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -lock=false -out=tfplan

      - name: Terraform Apply
        run: terraform apply -lock=false -auto-approve tfplan

      - name: Save Terraform Outputs to File
        run: terraform output > tf_outputs.txt

      - name: Check if MY_PAT is set
        run: |
          if [ -z "$MY_PAT" ]; then
            echo "❌ MY_PAT is empty"
            exit 1
          else
            echo "✅ MY_PAT is set. Length: ${#MY_PAT}"
          fi
        shell: bash
        env:
          MY_PAT: ${{ secrets.MY_PAT }}



      - name: Commit and Push Outputs File
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://${{ secrets.MY_PAT }}@github.com/Kalukwo/KejaHUnTinfrastructure.git
          git add tf_outputs.txt
          git commit -m "Save Terraform outputs" || echo "Nothing to commit"
          git push origin HEAD
        shell: bash

