name: Destroy Gateway Infrastructure
on:
  workflow_dispatch: # Manually triggered

jobs:
  destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
    env:
      TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
      TF_VAR_ami_id: ${{ secrets.AMI_ID }}
      TF_VAR_instance_type: ${{ secrets.INSTANCE_TYPE }}
      TF_VAR_key_name: ${{ secrets.KEY_NAME }}
      TF_VAR_security_group_id: ${{ secrets.SECURITY_GROUP_ID }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
          
      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Destroy
        run: terraform destroy -lock=false -auto-approve -target='module.aws_ec2.aws_instance.gateway'
